name: Build and test package

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build_and_test:
    name: Test on Python ${{ matrix.python }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["2.7", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox and any other packages
        run: pip install tox

      - name: Run tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py
